# Generated by Django 5.0.2 on 2024-04-09 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=50)),
                ('breed_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('size_preference', models.CharField(max_length=20)),
                ('age_preference', models.CharField(max_length=20)),
                ('activity_level_preference', models.CharField(max_length=50)),
                ('temperament_preference', models.CharField(max_length=50)),
                ('compatibility_with_other_pets', models.CharField(blank=True, max_length=100, null=True)),
                ('compatibility_with_children', models.CharField(blank=True, max_length=100, null=True)),
                ('grooming_needs', models.CharField(max_length=100)),
                ('living_environment', models.CharField(max_length=100)),
                ('time_commitment', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
