# Generated by Django 5.0.2 on 2024-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='activity_level_preference',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='age_preference',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='compatibility_with_children',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='compatibility_with_other_pets',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='size_preference',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='temperament_preference',
        ),
        migrations.RemoveField(
            model_name='adoptionpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='adoptionpreference',
            name='activity_level',
            field=models.CharField(choices=[('high', 'High-energy'), ('medium', 'Medium-energy'), ('low', 'Low-energy')], default=1, max_length=10, verbose_name='Activity Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpreference',
            name='age',
            field=models.CharField(choices=[('any', 'Any Age'), ('young', 'Young (0-2 years)'), ('adult', 'Adult (3-8 years)'), ('senior', 'Senior (9+ years)')], default=1, max_length=10, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpreference',
            name='compatibility_with_other_pets_or_children',
            field=models.CharField(default=1, max_length=250, verbose_name='Compatibility with Other Pets or Children'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpreference',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=1, max_length=10, verbose_name='Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptionpreference',
            name='temperament',
            field=models.CharField(choices=[('playful', 'Playful'), ('affectionate', 'Affectionate'), ('independent', 'Independent')], default=1, max_length=15, verbose_name='Temperament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionpreference',
            name='breed_preference',
            field=models.CharField(default=1, max_length=250, verbose_name='Breed Preference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionpreference',
            name='grooming_needs',
            field=models.CharField(choices=[('high', 'High maintenance'), ('low', 'Low maintenance')], max_length=10, verbose_name='Grooming Needs'),
        ),
        migrations.AlterField(
            model_name='adoptionpreference',
            name='living_environment',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House with a yard')], max_length=10, verbose_name='Living Environment'),
        ),
        migrations.AlterField(
            model_name='adoptionpreference',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10, verbose_name='Pet Type'),
        ),
        migrations.AlterField(
            model_name='adoptionpreference',
            name='time_commitment',
            field=models.CharField(choices=[('1', '1 hour or less'), ('2', '1-2 hours'), ('3', '2-3 hours'), ('4', '3+ hours')], max_length=1, verbose_name='Time Commitment'),
        ),
    ]
