# Generated by Django 5.0.3 on 2024-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='map',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
