# Generated by Django 5.0.3 on 2024-04-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0002_customuser_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='map',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
