# Generated by Django 5.0.2 on 2024-03-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0003_remove_customuser_phone_number_shelter_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelterUser',
        ),
    ]
