# Generated by Django 5.0.2 on 2024-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0004_delete_shelteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='name',
            new_name='shelter_name',
        ),
        migrations.AddField(
            model_name='shelter',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
