# Generated by Django 5.0.2 on 2024-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0005_rename_name_shelter_shelter_name_shelter_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
