# Generated by Django 5.0.2 on 2024-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0006_alter_shelter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
