# Generated by Django 5.0.2 on 2024-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0007_alter_shelter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
