# Generated by Django 5.0.2 on 2024-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0008_shelter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
