# Generated by Django 5.0.2 on 2024-04-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0011_remove_shelter_is_active_remove_shelter_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='username',
        ),
    ]
