# Generated by Django 5.0.2 on 2024-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0012_remove_shelter_email_remove_shelter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_shelter',
            field=models.BooleanField(default=False),
        ),
    ]
