# Generated by Django 5.0.2 on 2024-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment_app', '0013_customuser_is_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='street_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
