# Generated by Django 5.0.2 on 2024-03-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter_app', '0003_application_message_application_pet_application_user'),
        ('user_managment_app', '0002_shelter_customuser_phone_number_shelteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_managment_app.shelter'),
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
