# Generated by Django 5.0.2 on 2024-04-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter_app', '0005_rename_shelter_id_pet_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Under_review', 'Under review'), ('adopted', 'Adopted'), ('cancelled', 'Cancelled')], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_shelter_app.application')),
            ],
        ),
    ]
