# Generated by Django 5.0.2 on 2024-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter_app', '0006_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Under_review', 'Under review'), ('adopted', 'Adopted'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
