# Generated by Django 5.0.2 on 2024-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter_app', '0007_application_status_delete_applicationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breeds',
            field=models.CharField(max_length=100),
        ),
    ]
